# Defines stages which are to be executed
stages:  
  - build

# Stage "ubuntu"
build-ubuntu-2004-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackup_*.deb build/
    - upload_build build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-2004-64
  
# Stage "ubuntu"
build-ubuntu-1804-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackup_*.deb build/
    - upload_build build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

# Stage "debian"
build-debian-10-64:  
  stage: build
  script:
    - mkdir build
    - sudo apt update && sudo apt install tibackuplib-dev -y
    - echo "y" | debuild -- clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - mv ../tibackup_*.deb build/
    - upload_build build/tibackup*.deb || true
    - sudo apt purge tibackuplib-dev -y && sudo apt autoremove -y

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64
