#!/bin/sh
set -e

case "$1" in
configure)
	if ! getent group tibackup >/dev/null; then
		addgroup --system tibackup
	fi
	systemctl is-active --quiet tibackupd && systemctl restart tibackupd
	;;
abort-upgrade|abort-remove|abort-deconfigure)
	;;
*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
