#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=tibackup
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/home/rene/DEV/bin/tiBackup
DAEMON_OPTS=""

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
		start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		rm $PIDFILE
        echo "."
	;;
  status)
        echo -n "Status of daemon $NAME: "
                if start-stop-daemon --status --pidfile $PIDFILE; then 
			echo "started"; exit 0;
		else
			echo "stopped"; exit 1;
		fi
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
		start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
		start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
		echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|status|restart}"
	exit 1
esac

exit 0

